### ISSUE TITLE
Missing RegExp.$*?

### ISSUE THREAD

**Issue by domenic** [claudepache/es-regexp-legacy-static-properties#12]
Per https://github.com/whatwg/javascript/issues/22 this is in all browsers.

**Comment by claudepache** [comment]
`RegExp.multiline` and its alias `RegExp['$*']`
- is absent from IE/Edge;
- is in the process of being removed from Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1219757;
- has been recently removed from Chrome, see https://bugs.chromium.org/p/v8/issues/detail?id=3870;
- is present in Safari, but is nonfunctional. See also https://bugs.webkit.org/show_bug.cgi?id=150714.

See also: [changes.md#features-not-described-here-and-implemented-by-some-browsers-only](https://github.com/claudepache/es-regexp-legacy-static-properties/blob/master/changes.md#features-not-described-here-and-implemented-by-some-browsers-only) in this repository.
