### ISSUE TITLE
Should legacy RegExp features be disabled for subclasses and/or cross-realm?

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-regexp-legacy-static-properties#2]
Consensus and browser implementation experience needed before this can be settled.

**Comment by claudepache** [comment]
According to comments from #3, we want to disable those feature in the cross-realm case.

**Comment by littledan** [comment]
I might have misunderstood, but I thought @erights was claiming that Firefox semantics would be fine here, at least with respect to cross-realm behavior. I'm not sure what the subclassing hazard is exactly, though.

**Comment by erights** [comment]
I think you did misunderstand. In any case, the behavior specified here -- censoring cross-realm leakage -- is best. It is also within the intersection semantics and so cannot break any cross-browser pages. Also wonderful to extend this to RegExp.prototype.compile! I am embarrassed to have missed that.

The subclassing hazard was new to me, but the reasoning is sound. I support it to.

**Comment by claudepache** [comment]
> I might have misunderstood, but I thought @erights was claiming that Firefox semantics would be fine here, at least with respect to cross-realm behavior.

For the static properties of RegExp: it's _possible_ that it is sufficient. In any case, for the regular user, it won’t make any difference (they will just not notice anything), and I am unwilling to think about possible corner situations around that edge case.

> I'm not sure what the subclassing hazard is exactly, though.

If you mean the motivation for disabling the nonstandard features for subclasses, I have two:
1. the one detailed in [subclass-restriction-motivation.md](subclass-restriction-motivation.md). (If that text is not clear, let me know);
2. it is a stick to let people understand that these methods are deprecated.

As the feature was suggested to me by @allenwb in https://github.com/tc39/ecma262/issues/137#issuecomment-155142065, he might have other motivations as well.
