### ISSUE TITLE
This proposal needs to explicitly specify the right annex

### ISSUE THREAD

**Issue by erights** [claudepache/es-regexp-legacy-static-properties#4]
I think this is intended for Annex B, which IIUC will classify it as normative-optional, which is what we need. If for some reason this is not targeted at Annex B, then it must explicitly state normative-optional.

IOW, an implementation without these features is still conforming. But an implementation with these features present is only conforming if these features operate as spec'ed.

I'll file a separate bug on the feature that should be mandatory rather than normative-optional.

**Comment by erights** [comment]
> I'll file a separate bug on the feature that should be mandatory rather than normative-optional.

Nevermind. I thought that RegExp.prototype.compile was normative. I love the restrictions you place on it here, and wanted to ensure they were as normative as .compile itself. However, .compile is in Annex B (whew!), so placing this in Annex B as well should have the desired effect.

**Comment by claudepache** [comment]
Yes, it was so evident to me that I forgot to say that all of this stuff belongs to Annex B.
