### ISSUE TITLE
Present as proposal to TC39

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-regexp-legacy-static-properties#9]
@erights, do you want to champion this?

**Comment by erights** [comment]
Yes, thanks.

@littledan, co-champion?

**Comment by littledan** [comment]
I'm happy that this work is going on, but I'm not prepared at the moment to sign up to looking deeply into web compatibility concerns and getting an early, correct implementation with good performance, and without those I'd feel uncomfortable calling myself a champion.

**Comment by erights** [comment]
@littledan Thanks for the quick response.

@claudepache I will still champion this. Though I would appreciate it if we can find a co-champion.

**Comment by erights** [comment]
Added to the agenda at https://github.com/tc39/agendas/blob/master/2016/05.md

**Comment by claudepache** [comment]
Since the proposal concerns also `RegExp.protototype.compile`, maybe rename it as "Legacy RegExp features"?

**Comment by erights** [comment]
Done. But what about the name of this repository? Shouldn't change likewise?
